"""vehicle model and colour column added in vehicle table

Revision ID: 10266d83314f
Revises: 6adae2ff6f67
Create Date: 2026-05-19 12:50:25.290944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '10266d83314f'
down_revision: Union[str, Sequence[str], None] = '6adae2ff6f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('vehicle_colour', sa.String(length=20), nullable=False))
    op.add_column('vehicles', sa.Column('vehicle_model', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'vehicle_model')
    op.drop_column('vehicles', 'vehicle_colour')
    # ### end Alembic commands ###
