"""add pickup lat lng to ride requests

Revision ID: 6adae2ff6f67
Revises: b54bc9785c75
Create Date: 2026-05-12 14:11:13.311438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6adae2ff6f67'
down_revision: Union[str, Sequence[str], None] = 'b54bc9785c75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ride_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ride_locations_id'), 'ride_locations', ['id'], unique=False)
    op.add_column('ride_requests', sa.Column('pickup_lat', sa.Float(), nullable=True))
    op.add_column('ride_requests', sa.Column('pickup_lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ride_requests', 'pickup_lng')
    op.drop_column('ride_requests', 'pickup_lat')
    op.drop_index(op.f('ix_ride_locations_id'), table_name='ride_locations')
    op.drop_table('ride_locations')
    # ### end Alembic commands ###
